# Site
name: '#innovate'
description: 'Digital Leadership.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/website'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    al:
      name:           Andreas Lezgus
      site:           https://www.lezgus.de
      avatar:         /assets/images/avatar1.jpg
      bio:            "Die Schule des Lebens kennt keine Ferien... ausprobieren, lernen, gelassen bleiben. "
      email:          info@lezgus.de
      twitter:        https://twitter.com/andreaslezgus



# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: al
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
