version: 0.1

phases:

  build:
    commands:

      - echo "******** Building Jekyll site ********"
      - bundle exec jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://www.value4free.de
