version: 0.2

phases:
  install:
    commands:
      - echo "******** Install Bundles ********"
      - bundle install
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - JEKYLL_ENV=production bundle exec jekyll build
artifacts:
  base-directory: '_site'
  files:
    - '**/*'
  name: lezgus.de-$(date +%Y-%m-%d-%H%M%S)
