   version: 0.2

   env:
   variables:
      S3_BUCKET: "www.value4free.de"

   phases:
   install:
      commands:
         - gem install bundler
         - bundle update
   build:
      commands:
         - bundle exec jekyll build
   post_build:
      commands:
         - aws s3 sync _site/ s3://$S3_BUCKET
